// AUTO-GENERATED by scripts/generate-sidebar.ts — do not edit by hand.
// Regenerated on every `vite dev` / `vite build`.
export const contractsSidebar = [
  {
    "text": "Overview",
    "link": "/contracts"
  },
  {
    "text": "Deployments",
    "link": "/contracts/deployments"
  },
  {
    "text": "Security",
    "link": "/contracts/security"
  },
  {
    "text": "Changelog",
    "link": "/contracts/changelog"
  },
  {
    "text": "Bridge Encoders",
    "collapsed": true,
    "items": [
      {
        "text": "AcrossV4BridgeEncoder.sol",
        "collapsed": true,
        "items": [
          {
            "text": "AcrossV4BridgeEncoder",
            "link": "/contracts/bridge-encoders/AcrossV4BridgeEncoder.sol/contract.AcrossV4BridgeEncoder"
          }
        ]
      },
      {
        "text": "CctpV2BridgeEncoder.sol",
        "collapsed": true,
        "items": [
          {
            "text": "CctpV2BridgeEncoder",
            "link": "/contracts/bridge-encoders/CctpV2BridgeEncoder.sol/contract.CctpV2BridgeEncoder"
          }
        ]
      },
      {
        "text": "LayerZeroV2BridgeEncoder.sol",
        "collapsed": true,
        "items": [
          {
            "text": "LayerZeroV2BridgeEncoder",
            "link": "/contracts/bridge-encoders/LayerZeroV2BridgeEncoder.sol/contract.LayerZeroV2BridgeEncoder"
          }
        ]
      }
    ]
  },
  {
    "text": "Factory",
    "collapsed": true,
    "items": [
      {
        "text": "ModuleFactory.sol",
        "collapsed": true,
        "items": [
          {
            "text": "ModuleFactory",
            "link": "/contracts/factory/ModuleFactory.sol/contract.ModuleFactory"
          }
        ]
      }
    ]
  },
  {
    "text": "Flash Loans",
    "collapsed": true,
    "items": [
      {
        "text": "FlashLoanModule.sol",
        "collapsed": true,
        "items": [
          {
            "text": "FlashLoanModule",
            "link": "/contracts/flash-loans/FlashLoanModule.sol/contract.FlashLoanModule"
          }
        ]
      }
    ]
  },
  {
    "text": "Interfaces",
    "collapsed": true,
    "items": [
      {
        "text": "AggregatorV2V3Interface.sol",
        "collapsed": true,
        "items": [
          {
            "text": "AggregatorV2V3Interface",
            "link": "/contracts/interfaces/AggregatorV2V3Interface.sol/interface.AggregatorV2V3Interface"
          }
        ]
      },
      {
        "text": "IAcrossV4BridgeEncoder.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IAcrossV4BridgeEncoder",
            "link": "/contracts/interfaces/IAcrossV4BridgeEncoder.sol/interface.IAcrossV4BridgeEncoder"
          }
        ]
      },
      {
        "text": "IAcrossV4SpokePool.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IAcrossV4SpokePool",
            "link": "/contracts/interfaces/IAcrossV4SpokePool.sol/interface.IAcrossV4SpokePool"
          }
        ]
      },
      {
        "text": "IBridgeComponent.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IBridgeComponent",
            "link": "/contracts/interfaces/IBridgeComponent.sol/interface.IBridgeComponent"
          }
        ]
      },
      {
        "text": "IBridgeEncoder.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IBridgeEncoder",
            "link": "/contracts/interfaces/IBridgeEncoder.sol/interface.IBridgeEncoder"
          }
        ]
      },
      {
        "text": "ICctpV2BridgeEncoder.sol",
        "collapsed": true,
        "items": [
          {
            "text": "ICctpV2BridgeEncoder",
            "link": "/contracts/interfaces/ICctpV2BridgeEncoder.sol/interface.ICctpV2BridgeEncoder"
          }
        ]
      },
      {
        "text": "ICctpV2TokenMessenger.sol",
        "collapsed": true,
        "items": [
          {
            "text": "ICctpV2TokenMessenger",
            "link": "/contracts/interfaces/ICctpV2TokenMessenger.sol/interface.ICctpV2TokenMessenger"
          }
        ]
      },
      {
        "text": "IFlashLoanModule.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IFlashLoanModule",
            "link": "/contracts/interfaces/IFlashLoanModule.sol/interface.IFlashLoanModule"
          }
        ]
      },
      {
        "text": "ILayerZeroV2BridgeEncoder.sol",
        "collapsed": true,
        "items": [
          {
            "text": "ILayerZeroV2BridgeEncoder",
            "link": "/contracts/interfaces/ILayerZeroV2BridgeEncoder.sol/interface.ILayerZeroV2BridgeEncoder"
          }
        ]
      },
      {
        "text": "IMakinaXContext.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IMakinaXContext",
            "link": "/contracts/interfaces/IMakinaXContext.sol/interface.IMakinaXContext"
          }
        ]
      },
      {
        "text": "IMakinaXGovernable.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IMakinaXGovernable",
            "link": "/contracts/interfaces/IMakinaXGovernable.sol/interface.IMakinaXGovernable"
          }
        ]
      },
      {
        "text": "IMakinaXModule.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IMakinaXModule",
            "link": "/contracts/interfaces/IMakinaXModule.sol/interface.IMakinaXModule"
          }
        ]
      },
      {
        "text": "IMakinaXRegistry.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IMakinaXRegistry",
            "link": "/contracts/interfaces/IMakinaXRegistry.sol/interface.IMakinaXRegistry"
          }
        ]
      },
      {
        "text": "IModuleFactory.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IModuleFactory",
            "link": "/contracts/interfaces/IModuleFactory.sol/interface.IModuleFactory"
          }
        ]
      },
      {
        "text": "IMorpho.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IMorpho",
            "link": "/contracts/interfaces/IMorpho.sol/interface.IMorpho"
          }
        ]
      },
      {
        "text": "IMorphoFlashLoanCallback.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IMorphoFlashLoanCallback",
            "link": "/contracts/interfaces/IMorphoFlashLoanCallback.sol/interface.IMorphoFlashLoanCallback"
          }
        ]
      },
      {
        "text": "IOFT.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IOFT",
            "link": "/contracts/interfaces/IOFT.sol/interface.IOFT"
          }
        ]
      },
      {
        "text": "IOracleRegistry.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IOracleRegistry",
            "link": "/contracts/interfaces/IOracleRegistry.sol/interface.IOracleRegistry"
          }
        ]
      },
      {
        "text": "ISafe.sol",
        "collapsed": true,
        "items": [
          {
            "text": "ISafe",
            "link": "/contracts/interfaces/ISafe.sol/interface.ISafe"
          }
        ]
      },
      {
        "text": "ISwapComponent.sol",
        "collapsed": true,
        "items": [
          {
            "text": "ISwapComponent",
            "link": "/contracts/interfaces/ISwapComponent.sol/interface.ISwapComponent"
          }
        ]
      },
      {
        "text": "IWeirollComponent.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IWeirollComponent",
            "link": "/contracts/interfaces/IWeirollComponent.sol/interface.IWeirollComponent"
          }
        ]
      },
      {
        "text": "IWeirollVM.sol",
        "collapsed": true,
        "items": [
          {
            "text": "IWeirollVM",
            "link": "/contracts/interfaces/IWeirollVM.sol/interface.IWeirollVM"
          }
        ]
      }
    ]
  },
  {
    "text": "Libraries",
    "collapsed": true,
    "items": [
      {
        "text": "DecimalsUtils.sol",
        "collapsed": true,
        "items": [
          {
            "text": "DecimalsUtils",
            "link": "/contracts/libraries/DecimalsUtils.sol/library.DecimalsUtils"
          }
        ]
      },
      {
        "text": "Errors.sol",
        "collapsed": true,
        "items": [
          {
            "text": "Errors",
            "link": "/contracts/libraries/Errors.sol/library.Errors"
          }
        ]
      }
    ]
  },
  {
    "text": "MakinaXModule.sol",
    "collapsed": true,
    "items": [
      {
        "text": "MakinaXModule",
        "link": "/contracts/MakinaXModule.sol/contract.MakinaXModule"
      }
    ]
  },
  {
    "text": "Module Components",
    "collapsed": true,
    "items": [
      {
        "text": "BridgeComponent.sol",
        "collapsed": true,
        "items": [
          {
            "text": "BridgeComponent",
            "link": "/contracts/module-components/BridgeComponent.sol/abstract.BridgeComponent"
          }
        ]
      },
      {
        "text": "OracleRegistry.sol",
        "collapsed": true,
        "items": [
          {
            "text": "OracleRegistry",
            "link": "/contracts/module-components/OracleRegistry.sol/abstract.OracleRegistry"
          }
        ]
      },
      {
        "text": "SwapComponent.sol",
        "collapsed": true,
        "items": [
          {
            "text": "SwapComponent",
            "link": "/contracts/module-components/SwapComponent.sol/abstract.SwapComponent"
          }
        ]
      },
      {
        "text": "WeirollComponent.sol",
        "collapsed": true,
        "items": [
          {
            "text": "WeirollComponent",
            "link": "/contracts/module-components/WeirollComponent.sol/abstract.WeirollComponent"
          }
        ]
      }
    ]
  },
  {
    "text": "Registry",
    "collapsed": true,
    "items": [
      {
        "text": "MakinaXRegistry.sol",
        "collapsed": true,
        "items": [
          {
            "text": "MakinaXRegistry",
            "link": "/contracts/registry/MakinaXRegistry.sol/contract.MakinaXRegistry"
          }
        ]
      }
    ]
  },
  {
    "text": "Utils",
    "collapsed": true,
    "items": [
      {
        "text": "MakinaXContext.sol",
        "collapsed": true,
        "items": [
          {
            "text": "MakinaXContext",
            "link": "/contracts/utils/MakinaXContext.sol/abstract.MakinaXContext"
          }
        ]
      },
      {
        "text": "MakinaXGovernable.sol",
        "collapsed": true,
        "items": [
          {
            "text": "MakinaXGovernable",
            "link": "/contracts/utils/MakinaXGovernable.sol/abstract.MakinaXGovernable"
          }
        ]
      }
    ]
  }
];
