import { readdirSync, readFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Generates a Vocs sidebar from the `src/pages` filesystem. Used for the
 * Contracts section, whose pages are auto-generated by `forge doc` and would be
 * tedious and error-prone to list by hand.
 *
 *  - Folders are categories. Their label/position come from `_category_.json`
 *    (label falls back to the title-cased folder name).
 *  - Files are links. Their label comes from frontmatter `sidebar_label` or
 *    `title`, then the first `# ` heading, then the title-cased file name.
 *    Their position comes from frontmatter `sidebar_position`.
 *  - Siblings are sorted by position ascending (items without a position come
 *    last), then alphabetically by label.
 */

type SidebarItem = {
  text: string;
  link?: string;
  collapsed?: boolean;
  items?: SidebarItem[];
};

// Locate `src/pages` robustly. At build the config runs from the project root,
// but `vocs preview` bundles the config into dist/server and runs it with a
// different cwd, so neither import.meta.url nor process.cwd() alone is reliable.
// Walk up from both anchors until an existing `src/pages` directory is found.
function findPagesDir(): string {
  const anchors = [dirname(fileURLToPath(import.meta.url)), process.cwd()];
  for (const anchor of anchors) {
    let dir = anchor;
    for (let i = 0; i < 6; i++) {
      const candidate = join(dir, "src/pages");
      if (existsSync(candidate)) return candidate;
      const parent = dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }
  return resolve(process.cwd(), "src/pages");
}

const PAGES_DIR = findPagesDir();

const NO_POSITION = Number.POSITIVE_INFINITY;

function titleCase(name: string): string {
  return name
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function parseFrontmatter(content: string): Record<string, string> {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const fields: Record<string, string> = {};
  for (const line of match[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    fields[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
  }
  return fields;
}

function firstHeading(content: string): string | undefined {
  const body = content.replace(/^---\r?\n[\s\S]*?\r?\n---/, "");
  const match = body.match(/^#\s+(.+?)\s*$/m);
  return match?.[1];
}

function routeFor(relPath: string): string {
  let route = `/${relPath.split("\\").join("/")}`.replace(/\.mdx?$/, "");
  route = route.replace(/\/index$/, "");
  return route === "" ? "/" : route;
}

type Entry = { position: number; label: string; item: SidebarItem };

function buildItems(absDir: string, relDir: string, depth: number, expandTop: boolean): SidebarItem[] {
  const entries: Entry[] = [];

  for (const name of readdirSync(absDir, { withFileTypes: true })) {
    if (name.name === "_category_.json") continue;

    if (name.isDirectory()) {
      const childAbs = join(absDir, name.name);
      const childRel = relDir ? `${relDir}/${name.name}` : name.name;
      const categoryPath = join(childAbs, "_category_.json");
      let label = titleCase(name.name);
      let position = NO_POSITION;
      if (existsSync(categoryPath)) {
        const meta = JSON.parse(readFileSync(categoryPath, "utf8"));
        if (typeof meta.label === "string") label = meta.label;
        if (typeof meta.position === "number") position = meta.position;
      }
      // Top-level sections can be expanded by default (per-sidebar opt-in);
      // nested sub-sections stay collapsed to keep the tree scannable.
      const collapsed = !(expandTop && depth === 0);
      entries.push({
        position,
        label,
        item: { text: label, collapsed, items: buildItems(childAbs, childRel, depth + 1, expandTop) },
      });
      continue;
    }

    if (!/\.mdx?$/.test(name.name)) continue;

    const childRel = relDir ? `${relDir}/${name.name}` : name.name;
    const content = readFileSync(join(absDir, name.name), "utf8");
    const fm = parseFrontmatter(content);
    const label =
      fm.sidebar_label ||
      fm.title ||
      firstHeading(content) ||
      titleCase(name.name.replace(/\.mdx?$/, ""));
    const position = fm.sidebar_position ? Number(fm.sidebar_position) : NO_POSITION;
    entries.push({
      position,
      label,
      item: { text: label, link: routeFor(childRel) },
    });
  }

  entries.sort((a, b) => a.position - b.position || a.label.localeCompare(b.label));
  return entries.map((entry) => entry.item);
}

export function generateSidebar(
  subdir: string,
  options?: { expandTopLevel?: boolean },
): SidebarItem[] {
  return buildItems(join(PAGES_DIR, subdir), subdir, 0, options?.expandTopLevel ?? false);
}
