// AUTO-GENERATED by scripts/generate-sidebar.ts — do not edit by hand.
// Regenerated on every `vite dev` / `vite build`.
export const contractsSidebar = [
  {
    "text": "Overview",
    "link": "/contracts"
  },
  {
    "text": "Deployments",
    "link": "/contracts/deployments"
  },
  {
    "text": "Security",
    "link": "/contracts/security"
  },
  {
    "text": "Changelog",
    "link": "/contracts/changelog"
  },
  {
    "text": "Bridge Encoders",
    "collapsed": true,
    "items": [
      {
        "text": "AcrossV4BridgeEncoder",
        "link": "/contracts/bridge-encoders/contract.AcrossV4BridgeEncoder"
      },
      {
        "text": "CctpV2BridgeEncoder",
        "link": "/contracts/bridge-encoders/contract.CctpV2BridgeEncoder"
      },
      {
        "text": "LayerZeroV2BridgeEncoder",
        "link": "/contracts/bridge-encoders/contract.LayerZeroV2BridgeEncoder"
      }
    ]
  },
  {
    "text": "Factory",
    "collapsed": true,
    "items": [
      {
        "text": "ModuleFactory",
        "link": "/contracts/factory/contract.ModuleFactory"
      }
    ]
  },
  {
    "text": "Flash Loans",
    "collapsed": true,
    "items": [
      {
        "text": "FlashLoanModule",
        "link": "/contracts/flash-loans/contract.FlashLoanModule"
      }
    ]
  },
  {
    "text": "Interfaces",
    "collapsed": true,
    "items": [
      {
        "text": "AggregatorV2V3Interface",
        "link": "/contracts/interfaces/interface.AggregatorV2V3Interface"
      },
      {
        "text": "IAcrossV4BridgeEncoder",
        "link": "/contracts/interfaces/interface.IAcrossV4BridgeEncoder"
      },
      {
        "text": "IAcrossV4SpokePool",
        "link": "/contracts/interfaces/interface.IAcrossV4SpokePool"
      },
      {
        "text": "IBridgeComponent",
        "link": "/contracts/interfaces/interface.IBridgeComponent"
      },
      {
        "text": "IBridgeEncoder",
        "link": "/contracts/interfaces/interface.IBridgeEncoder"
      },
      {
        "text": "ICctpV2BridgeEncoder",
        "link": "/contracts/interfaces/interface.ICctpV2BridgeEncoder"
      },
      {
        "text": "ICctpV2TokenMessenger",
        "link": "/contracts/interfaces/interface.ICctpV2TokenMessenger"
      },
      {
        "text": "IFlashLoanModule",
        "link": "/contracts/interfaces/interface.IFlashLoanModule"
      },
      {
        "text": "ILayerZeroV2BridgeEncoder",
        "link": "/contracts/interfaces/interface.ILayerZeroV2BridgeEncoder"
      },
      {
        "text": "IMakinaXContext",
        "link": "/contracts/interfaces/interface.IMakinaXContext"
      },
      {
        "text": "IMakinaXGovernable",
        "link": "/contracts/interfaces/interface.IMakinaXGovernable"
      },
      {
        "text": "IMakinaXModule",
        "link": "/contracts/interfaces/interface.IMakinaXModule"
      },
      {
        "text": "IMakinaXRegistry",
        "link": "/contracts/interfaces/interface.IMakinaXRegistry"
      },
      {
        "text": "IModuleFactory",
        "link": "/contracts/interfaces/interface.IModuleFactory"
      },
      {
        "text": "IMorpho",
        "link": "/contracts/interfaces/interface.IMorpho"
      },
      {
        "text": "IMorphoFlashLoanCallback",
        "link": "/contracts/interfaces/interface.IMorphoFlashLoanCallback"
      },
      {
        "text": "IOFT",
        "link": "/contracts/interfaces/interface.IOFT"
      },
      {
        "text": "IOracleRegistry",
        "link": "/contracts/interfaces/interface.IOracleRegistry"
      },
      {
        "text": "ISafe",
        "link": "/contracts/interfaces/interface.ISafe"
      },
      {
        "text": "ISwapComponent",
        "link": "/contracts/interfaces/interface.ISwapComponent"
      },
      {
        "text": "IWeirollComponent",
        "link": "/contracts/interfaces/interface.IWeirollComponent"
      },
      {
        "text": "IWeirollVM",
        "link": "/contracts/interfaces/interface.IWeirollVM"
      }
    ]
  },
  {
    "text": "Libraries",
    "collapsed": true,
    "items": [
      {
        "text": "DecimalsUtils",
        "link": "/contracts/libraries/library.DecimalsUtils"
      },
      {
        "text": "Errors",
        "link": "/contracts/libraries/library.Errors"
      }
    ]
  },
  {
    "text": "MakinaXModule",
    "link": "/contracts/contract.MakinaXModule"
  },
  {
    "text": "Module Components",
    "collapsed": true,
    "items": [
      {
        "text": "BridgeComponent",
        "link": "/contracts/module-components/abstract.BridgeComponent"
      },
      {
        "text": "OracleRegistry",
        "link": "/contracts/module-components/abstract.OracleRegistry"
      },
      {
        "text": "SwapComponent",
        "link": "/contracts/module-components/abstract.SwapComponent"
      },
      {
        "text": "WeirollComponent",
        "link": "/contracts/module-components/abstract.WeirollComponent"
      }
    ]
  },
  {
    "text": "Registry",
    "collapsed": true,
    "items": [
      {
        "text": "MakinaXRegistry",
        "link": "/contracts/registry/contract.MakinaXRegistry"
      }
    ]
  },
  {
    "text": "Utils",
    "collapsed": true,
    "items": [
      {
        "text": "MakinaXContext",
        "link": "/contracts/utils/abstract.MakinaXContext"
      },
      {
        "text": "MakinaXGovernable",
        "link": "/contracts/utils/abstract.MakinaXGovernable"
      }
    ]
  }
];
