import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { generateSidebar } from "../sidebar.js";

// Runs at build time (on the build machine, where `src/pages` exists) and bakes
// the Contracts sidebar into a static `sidebar.generated.ts`. The deployed config
// imports that literal instead of scanning the filesystem, which does not exist in
// the serverless runtime (`/var/task`). See sidebar.ts for the scan semantics.

const contracts = generateSidebar("contracts");
const out = fileURLToPath(new URL("../sidebar.generated.ts", import.meta.url));
const banner =
  "// AUTO-GENERATED by scripts/generate-sidebar.ts — do not edit by hand.\n" +
  "// Regenerated on every `vite dev` / `vite build`.\n";

writeFileSync(
  out,
  `${banner}export const contractsSidebar = ${JSON.stringify(contracts, null, 2)};\n`,
);
